### ISSUE TITLE
plot=FALSE? / df

### ISSUE THREAD

**Issue by ChristophHanck** [DInfanger/pvaluefunctions#1]
Thanks for this nice package!

Two minor suggestions:

1) It would seem nice to allow for an optional plot=F argument, like in, e.g., acf, so that the user is free to first create objects for the plots to then arrange them in, e.g,. several panels via layout.
2) Is the df argument for lm objects really necessary? See, e.g., my recreation of your example below? If so, for some other purpose, could the default in case of type="linreg" not be retrieved by allowing users to pass an lm object with indication of which parameter(s) they are interested in rather than the coefficient itself.? In that case, you could simply set df=summary(lmobject)$df.

```
mod <- lm(Infant.Mortality~Agriculture + Fertility + Examination, data = swiss)

lm.mod <- summary(mod)

coef.ag <- lm.mod$coefficients[2,1]
se.ag <- lm.mod$coefficients[2,2]
steps <- 99
levels <- seq(0.99, 0.01, length.out = steps)
CIs <- sapply(levels, function(j) confint(mod, "Agriculture", level = j))
xax <- c(CIs[1,], coef.ag, rev(CIs[2,]))
yax <- c(rev(levels), 1, levels)

plot(xax, yax, type="l", lwd=2, col="lightblue")
abline(h=0.05, lty=2)
abline(h=0.1, lty=2)
abline(h=0.2, lty=2)
```

**Comment by DInfanger** [comment]
Dear Christoph

Thank you very much for the feedback. I'm sorry that I did not reply earlier; I didn't log into GitHub for quite a while.

To address your suggestions:

> 1. It would seem nice to allow for an optional plot=F argument, like in, e.g., acf, so that the user is free to first create objects for the plots to then arrange them in, e.g,. several panels via layout.

That's a good suggestion. I included this option in the newest version (v1.5.0) which is released on CRAN now.

Because the function returns the ggplot2-object by default, you already have the ability to manipulate them to a certain extent after creation. I did that to create the plots in our [paper](https://onlinelibrary.wiley.com/doi/abs/10.1002/sim.8293). The corresponding [code](https://github.com/DInfanger/pvalue_functions/blob/master/paper_plots.R) can be found in my other [repository](https://github.com/DInfanger/pvalue_functions). You could, for example, create multiple p-value functions, store the results and combine them using ggpubr or something like that. But I agree that it's convenient to just omit the plot altogether.

> 2. Is the df argument for lm objects really necessary? See, e.g., my recreation of your example below? If so, for some other purpose, could the default in case of type="linreg" not be retrieved by allowing users to pass an lm object with indication of which parameter(s) they are interested in rather than the coefficient itself.? In that case, you could simply set df=summary(lmobject)$df.

The [concurve](https://cran.r-project.org/package=concurve) package implements your suggested approach where you can pass objects such as `lm` or `glm` directly as inputs. It has the added advantage to create the _p_-value functions from profile likelihood confidence intervals.

When I first started the package, I designed it to directly accept different R objects (from `lm`, `cor`, `glm` etc.). Because it proved difficult and tedious to create the p-value functions for a wide array of different input objects, I then opted for the current approach which implements a more general approach that is more flexible imo. I'm sorry to say that I'm hesitant to change my approach at that stage.

A quick and dirty compromise that kind of mimicks your approach would be the following:

```
# Set the desired coefficient to plot
my_coef <- "Agriculture"

mod <- lm(Infant.Mortality~Agriculture + Fertility + Examination, data = swiss)

res <- conf_dist(
  estimate = coef(mod)[my_coef]
  , df = mod$df.residual
  , stderr = coef(summary(mod))[my_coef, 2]
  , type = "linreg"
  , plot_type = "p_val"
  , n_values = 1e4L
  , est_names = my_coef
  , conf_level = c(0.95, 0.90, 0.80)
  , null_values = c(0)
  , trans = "identity"
  , alternative = "two_sided"
  , log_yaxis = TRUE
  , cut_logyaxis = 0.05
  , xlab = "Coefficient Agriculture"
  , xlim = c(-0.12, 0.065)
  , together = FALSE
  , plot_p_limit = 1 - 0.999
  , plot_counternull = FALSE
)
```
All you'd have to do is to change `my_coef` and the correct coefficient and standard error will be extracted from the `lm` object. The residual degrees of freedom are also automatically extracted from the `lm` object.

Thanks again for your interest in the package. Let me know if you have more suggestions for improvement.
